### ISSUE TITLE
Документация

### ISSUE THREAD

**Issue by vavileno** [yandex-money/yandex-checkout-sdk-php#1]
Добрый день.
Планируется ли создание руководства программиста по использованию API или придется самому изучать код?

**Comment by ikarmanov** [comment]
Добрый день.

Скоро на странице [инструкции](https://kassa.yandex.ru/docs/guides/) добавятся примеры на PHP (на базе SDK). Сейчас уже есть примеры на PHP (на базе SDK) в [документации](https://kassa.yandex.ru/docs/checkout-api/) к API Яндекс.Кассы.

Если есть трудности с чем-то конкретным, то сообщите об этом.
