### ISSUE TITLE
Income amount

### ISSUE THREAD

**Issue by vitalypanait** [yandex-money/yandex-checkout-sdk-php#105]
При получении данных о платеже `YandexCheckout::createPayment` возвращается информация:
```
"income_amount" : {
    "value" : "965.00",
    "currency" : "RUB"
  },
```
Как я понимаю это сумма платежа с учетом комиссии. Можете добавить эту информацию в PaymentInterface?

**Comment by ostulov** [comment]
Добрый день!

Благодарю за обращение, добавим новый параметр.

**Comment by vitalypanait** [comment]
@ostulov а когда ожидать?

**Comment by vitalypanait** [comment]
@ostulov ?

**Comment by ostulov** [comment]
Добрый день!

Добавление income_amount выйдет в следующем обновлении SDK, которое ожидает добавления еще одной фичи.

**Comment by vitalypanait** [comment]
@ostulov а когда ожидать след. обновления?

**Comment by ostulov** [comment]
Добрый день!

Выложили обновление SDK.
