### ISSUE TITLE
Ошибка при создании рекуррентного платежа, если отозвано разрешение на оплату

### ISSUE THREAD

**Issue by alexxxst** [yandex-money/yandex-checkout-sdk-php#107]
Есть сохранённый платёж, пытаюсь провести по нему новый платёж, но, как оказалось, разрешение на оплату уже отозвано клиентом, в результате ошибка:

> YandexCheckout\Common\Exceptions\InvalidPropertyValueException: Invalid reason value: "permission_revoked" in /var/www/yii2/vendor/yandex-money/yandex-checkout-sdk-php/lib/Model/CancellationDetails.php:137
> Stack trace:
> #0 /var/www/yii2/vendor/yandex-money/yandex-checkout-sdk-php/lib/Model/CancellationDetails.php(64): YandexCheckout\Model\CancellationDetails->setReason('permission_revo...')
> #1 /var/www/yii2/vendor/yandex-money/yandex-checkout-sdk-php/lib/Request/Payments/AbstractPaymentResponse.php(163): YandexCheckout\Model\CancellationDetails->__construct('yandex_checkout', 'permission_revo...')
> #2 /var/www/yii2/vendor/yandex-money/yandex-checkout-sdk-php/lib/Client.php(245): YandexCheckout\Request\Payments\AbstractPaymentResponse->__construct(Array)
> #3 /var/www/panel3/panel/components/payment/Kassa.php(511): YandexCheckout\Client->createPayment(Object(YandexCheckout\Request\Payments\CreatePaymentRequest), '5eb51eaaa8b482....')

Вероятно, что в _/vendor/yandex-money/yandex-checkout-sdk-php/lib/Model/CancellationDetailsReasonCode.php нет нужного варианта отказа.
Как быть или как поймать такое без костылей?

**Comment by ostulov** [comment]
Добрый день!

Благодарю за обращение, подготовим в sdk исправление для такого случая.

**Comment by ostulov** [comment]
Добавлено в v1.6.0
