### ISSUE TITLE
Некорректный код карты

### ISSUE THREAD

**Issue by mdevian** [yandex-money/yandex-checkout-sdk-php#18]
На клиенте (lib/Model/PaymentMethod/PaymentMethodCardType) код карты:
`const MIR = 'Mir';`

API возвращает код 'MIR'

Т.к. коды карт не кастятся в единый регистр, бросается эксепшн и объект платежа не создается.

**Comment by shoomlix** [comment]
Получилось решить у Вас? А то уже неделю мучаемся с этим багом.

**Comment by mdevian** [comment]
Ну пришлось создать локальную копию и сделать кастинг уже там.

**Comment by shoomlix** [comment]
Понял.
А как оказалось, нужно было только эту строчку с константой как раз и заменить на эту
const MIR = 'MIR';

Только сегодня написал один из разработчиков этого компонента эту информацию.

**Comment by mdevian** [comment]
Ну так об этом я тут и написал)

**Comment by shoomlix** [comment]
Понял)))

**Comment by ikarmanov** [comment]
Добрый день. Проблему исправили в #19
