### ISSUE TITLE
Не получается добавить description в платеж -  всегда null!

### ISSUE THREAD

**Issue by alexmixaylov** [yandex-money/yandex-checkout-sdk-php#21]
Пытаюсь создать платеж
все нормально отрабатывает, но никак не получается добавить дескрипшн к платежу
дамп показывает значение NULL 
в инструкции написано, что дескрипшн добавляется ка строковое значение
пытаюсь добавить в массив параметров createPayment , но увы
подскажите пожалуйста что делаю не так

причем описание появляется в кабинете яндекс кассы
но показать его человеку при оплате и обработать после оплаты - нет

>             $config_ym = self::configYM();
>             $client = new Client();
>             $client->setAuth($config_ym->shopId, $config_ym->yandexKey);
> 
>             $response = $client->createPayment(array(
>                 'description' => 'описание',
>                 'amount' => array(
>                     'value' => 100,
>                     'currency' => 'RUB',
>                 ),
>                 'payment_method_data' => array(
>                     'type' => 'bank_card',
>                 ),
>                 'confirmation' => array(
>                     'type' => 'redirect',
>                     'return_url' => $config_ym->returnUrl,
>                 ),
>                 'metadata' => ['something'=>'something']
>                ),
>                 uniqid('', true)
>             );
>             return $response;

**Comment by ostulov** [comment]
Добрый день!

Если проблема актуальна, напишите в техподдержку Яндекс.Кассы по почте yamoney_shop@yamoney.ru с указанием Вашего shopid.
