### ISSUE TITLE
Не проходит testAutoload

### ISSUE THREAD

**Issue by Alexander-Permyakov** [yandex-money/yandex-checkout-sdk-php#3]
![image](https://user-images.githubusercontent.com/15966815/32729477-c53ca79a-c8a5-11e7-9d48-405aba9aefc3.png)

**Comment by actofgod** [comment]
Баг в тесте исправим в 1.0.2 версии SDK.

**Comment by Alexander-Permyakov** [comment]
Спасибо, с вами приятно работать
