### ISSUE TITLE
Нет доступа к сырым данным

### ISSUE THREAD

**Issue by kznamenskiy** [yandex-money/yandex-checkout-sdk-php#37]
Вызывая $client->createPayment($data); всегда возвращается объект CreatePaymentResponse, конструктор которого может быть своевременно не обновлен, соответственно новые данные которые уже есть в сырых данных ($resultArray) полученных по апи никак невозможно достать.
Приходится делать обертки над такой библиотекой, копировать код метода и добавлять возможность получить сырые данные.

**Comment by kznamenskiy** [comment]
Например почему-то в этом объекте CreatePaymentResponse полностью не учитывается поле "test" которое присутствует в массиве сырых данных ($resultArray)

**Comment by ostulov** [comment]
Благодарю за замечание, подумаем над решением.

**Comment by ostulov** [comment]
Было исправлено в версии 1.1.5

**Comment by kznamenskiy** [comment]
если речь именно о моем замечании - то нет, оно никак не исправлено/реализовано в версии 1.1.5
