### ISSUE TITLE
Яндекс.Касса больше не возвращает HTTP-код 202

### ISSUE THREAD

**Issue by kznamenskiy** [yandex-money/yandex-checkout-sdk-php#38]
Согласно информации на странице https://kassa.yandex.ru/docs/checkout-api/#istoriq-izmenenij
12 СЕНТЯБРЯ 2018
Яндекс.Касса больше не возвращает HTTP-код 202 («запрос обрабатывается») — в ответ придет либо «успех», либо «неудача».

А в коде библиотеки повторная отправка запроса (метод Client::execute) выполняется только в случае возврата именно этого (202го) кода.

**Comment by ostulov** [comment]
Да, в модуле пока остается код для повтора запроса при получении 202 кода ответа.
Для повтора запроса в других случаях необходимо формировать новый запрос.
