### ISSUE TITLE
Неработает YandexCheckout\Model\Payment::fromArray

### ISSUE THREAD

**Issue by Alexander-Permyakov** [yandex-money/yandex-checkout-sdk-php#4]
На URL для уведомлений приходит Json такого вида:
`{"type":"notification","event":"payment.waiting_for_capture","object":{"id":"21a65574-000f-5075-b000-0da812966c0e","status":"waiting_for_capture","paid":true,"amount":{"value":"19.99","currency":"RUB"},"created_at":"2017-11-21T15:09:40.692Z","expires_at":"2017-11-28T15:10:25.546Z","metadata":{"main_payment_id":"107"},"payment_method":{"type":"bank_card","id":"21a65574-000f-5075-b000-0da812966c0e","saved":false,"card":{"last4":"1026","expiry_month":"11","expiry_year":"2021","card_type":"Unknown"},"title":"Bank card *1026"},"recipient":{"account_id":"500303","gateway_id":"1500303"}}}`

Принимаю эти данные и пытаюсь создать объект Payment:

use YandexCheckout\Model\Payment as YandexPayment;
...
$postJson = file_get_contents('php://input');
$postJson = trim($postJson);
$post = json_decode($postJson, true);
$inputPayment = new YandexPayment();
$inputPayment->fromArray($post['object']);
// код ниже не выполняется, видимо из-за ошибки PHP, т.к. никакие эксепшены из fromArray не выкидываются

**Comment by actofgod** [comment]
Для нотификаций, приходящих от кассы, существует отдельный класс [YandexCheckout\Model\Notification\NotificationWaitingForCapture](lib/Model/Notification/NotificationWaitingForCapture.php) с которым работа должна происходить примерно так:
```php
use YandexCheckout\Model\Notification\NotificationWaitingForCapture;
use YandexCheckout\Model\PaymentStatus;

$postJson = file_get_contents('php://input');
$postJson = trim($postJson);
$postData = json_decode($postJson, true);

$notification = new NotificationWaitingForCapture($postData);
$payment = $notification->getObject();
if ($payment->getStatus() === PaymentStatus::WAITING_FOR_CAPTURE) {
    // платёж ожидает подтверждения
} elseif ($payment->getStatus() === PaymentStatus::CANCELED) {
    // платёж был отменён
} elseif ($payment->getStatus() === PaymentStatus::SUCCEEDED) {
    // платёж уже был подтверждён
}
```

**Comment by Alexander-Permyakov** [comment]
Спасибо, в документации https://kassa.yandex.ru/docs/checkout-api/ не видел упоминания о классе NotificationWaitingForCapture
