### ISSUE TITLE
При создании платежа в ответе API может отсутствовать поле "auth_code" в "authorization_details"

### ISSUE THREAD

**Issue by Heliocuda** [yandex-money/yandex-checkout-sdk-php#45]
При создании платежа в ответе API может отсутствовать поле "auth_code" в "authorization_details" при этом `YandexCheckout\Request\Payments\AbstractPaymentResponse->__construct` падает с ошибкой 'Undefined index: auth_code', в строке https://github.com/yandex-money/yandex-checkout-sdk-php/blob/55e746d70bd1f110b3f8dcccc6e7f0acd65b6c44/lib/Request/Payments/AbstractPaymentResponse.php#L119 

Пример ответа с отсутствующим полем:
```javascript
{
	"id": "*****",
	"status": "canceled",
	"paid": false,
	"amount": {
		"value": "1.00",
		"currency": "RUB"
	},
	"authorization_details": {
		"rrn": "*****"
	},
	"created_at": "2018-12-04T06:30:56.984Z",
	"description": "*****",
	"metadata": {
		"*****": "*****"
	},
	"payment_method": {
		"type": "bank_card",
		"id": "*****",
		"saved": true
	},
	"recipient": {
		"account_id": "*****",
		"gateway_id": "*****"
	},
	"test": false,
	"cancellation_details": {
		"party": "payment_network",
		"reason": "payment_method_restricted"
	}
}
```

**Comment by ostulov** [comment]
Добрый день!

Благодарю за сообщение, подготовим исправление для данной ошибки.

**Comment by eightyeight** [comment]
#46

**Comment by Heliocuda** [comment]
Исправили только в `/lib/Request/Payments/PaymentsResponse.php`, а про `lib/Request/Payments/AbstractPaymentResponse.php` забыли.

**Comment by ostulov** [comment]
Спасибо, проверим.

**Comment by Heliocuda** [comment]
Было исправлено в #49
