### ISSUE TITLE
Отсутствует перечисление ставок НДС и кодов системы налогообложения

### ISSUE THREAD

**Issue by Alexander-Permyakov** [yandex-money/yandex-checkout-sdk-php#5]
При создании платежа с данными чека для онлайн кассы требуется указывать значение поля vat_code  (Ставка НДС, число от 1 до 6).

Какое значение в поле vat_code я должен указать, если у меня ставка НДС 18%?
Какое значение в поле vat_code я должен указать, если у меня ставка НДС 10%?
Какое значение в поле vat_code я должен указать, если у меня ставка НДС 0%?
Какое значение в поле vat_code я должен указать, если у меня ставка НДС 10/110?
Какое значение в поле vat_code я должен указать, если у меня ставка НДС 18/118?
Какое значение в поле vat_code я должен указать, если товар НДС не облагается?

Аналогично с полем tax_system_code (Код системы налогообложения. Число от 1 до 6).
Какое значение в поле tax_system_code я должен указать, если у меня, например, упрощенная система налогообложения?

В документации https://kassa.yandex.ru/docs/checkout-api/#sozdanie-platezha, https://kassa.yandex.ru/docs/guides/ я не нашел ссылок на классификаторы ставок НДС и кодов системы налогообложения.

**Comment by actofgod** [comment]
Коды ставок полностью совпадают со [старым API](https://tech.yandex.ru/money/doc/payment-solution/payment-form/payment-form-receipt-docpage/) - параметр tax для товара:

Ставка НДС. Возможные значения — число от 1 до 6:
* 1 — без НДС;
* 2 — НДС по ставке 0%;
* 3 — НДС чека по ставке 10%;
* 4 — НДС чека по ставке 18%;
* 5 — НДС чека по расчетной ставке 10/110;
* 6 — НДС чека по расчетной ставке 18/118.

**Comment by Alexander-Permyakov** [comment]
Спасибо
