### ISSUE TITLE
Invalid payment method data type "tinkoff_bank"

### ISSUE THREAD

**Issue by burovgleb** [yandex-money/yandex-checkout-sdk-php#50]
Необходимо добавить новый метод оплаты tinkoff_bank.

Invalid payment method data type "tinkoff_bank"
#0 /yandex-checkout-sdk-php/lib/Model/PaymentMethod/PaymentMethodFactory.php(89): YandexCheckout\Model\PaymentMethod\PaymentMethodFactory->factory('tinkoff_bank')
#1 /yandex-checkout-sdk-php/lib/Request/Payments/AbstractPaymentResponse.php(135): YandexCheckout\Model\PaymentMethod\PaymentMethodFactory->factoryFromArray(Array)
#2 /yandex-checkout-sdk-php/lib/Request/Payments/AbstractPaymentResponse.php(63): YandexCheckout\Request\Payments\AbstractPaymentResponse->factoryPaymentMethod(Array)
#3 /yandex-checkout-sdk-php/lib/Model/Notification/NotificationSucceeded.php(89): YandexCheckout\Request\Payments\AbstractPaymentResponse->__construct(Array)

**Comment by ostulov** [comment]
Добрый день!

Новый способ оплаты будет добавлен на днях.

**Comment by ostulov** [comment]
Выложено в версии v1.1.6

**Comment by mdevian** [comment]
Версии 1.1.6 нет в композере, нельзя нормально обновить. Сделайте что-нибудь)

**Comment by ostulov** [comment]
> Версии 1.1.6 нет в композере, нельзя нормально обновить. Сделайте что-нибудь)

Проверьте еще раз, она должна быть.

**Comment by mdevian** [comment]
Да, к тому моменту уже появилась.
