### ISSUE TITLE
При передаче recipient необходимо указывать account_id, что не соответствует документации

### ISSUE THREAD

**Issue by mininzidane** [yandex-money/yandex-checkout-sdk-php#52]
При создании платежа в методе vendor/yandex-money/yandex-checkout-sdk-php/lib/Request/Payments/CreatePaymentRequestBuilder::build() идет проверка на наличие `account_id`, хотя в документации указан только `gateway_id`:
`
        $accountId = $this->recipient->getAccountId();
        $gatewayId = $this->recipient->getGatewayId();
        if (!empty($accountId) && !empty($gatewayId)) {
            $this->currentObject->setRecipient($this->recipient);
        }
`

**Comment by ostulov** [comment]
Добрый день!

Параметр account_id нужен для авторизации, так что он необходим.

**Comment by mininzidane** [comment]
@ostulov для авторизации ведь есть отдельный метод vendor/yandex-money/yandex-checkout-sdk-php/lib/Client::setAuth() куда мы передает shopId. И его же нужно передавать в accountId, получается? И если accountId необходим для авторизации, почему напрямую в API можно без него послать запрос, с одним только gatewayId?

**Comment by ostulov** [comment]
Запрос с одним gatewayId пройдет, если только один gatewayId привязан к accountId. 
Мы проверим подробности, почему стоит проверка на наличие accountId, и при необходимости поправим условия в sdk.

**Comment by ostulov** [comment]
Исправлено в v1.3.0
