### ISSUE TITLE
Позиции с отрицательной ценой

### ISSUE THREAD

**Issue by ilyahoilik** [yandex-money/yandex-checkout-sdk-php#6]
Здравствуйте!

Есть ли возможность добавлять в чек, формируемый для 54-ФЗ, позиции с отрицательной ценой? Например, скидочные купоны определенного номинала или подарочные сертификаты?

Заранее спасибо за ответ.

**Comment by actofgod** [comment]
Позиции с отрицательной ценой в данный момент добавлять нельзя.

В свою очередь, при попытке создания платежа с включенной фискализацией, если сумма стоимостей позиций в чеке не будет совпадать с суммой самого платежа, Яндекс.Касса платёж не примет. Поэтому сейчас необходимо:
* либо перед установкой позиций чека рассчитывать стоимость позиций с учётом применяемых скидок
* либо, как было предложено выше, воспользоваться методом normalize:
```php
// ... создание объекта платежа
// ...

/** @var \YandexCheckout\Request\Payments\CreatePaymentRequest $payment */
if ($payment->hasReceipt() && $payment->getReceipt()->notEmpty()) {
    // применение скидок ко всем позициям в чеке, если чек имеется и не пустой
    $payment->getReceipt()->normalize($payment->getAmount());
}
// создание платежа
$client->createPayment($payment, uniqid('', true));
```
