### ISSUE TITLE
Нет возможности создать платеж

### ISSUE THREAD

**Issue by eldario** [yandex-money/yandex-checkout-sdk-php#66]
Согласно [документации](https://kassa.yandex.ru/developers/api#%D1%81%D0%BE%D0%B7%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5_%D0%BF%D0%BB%D0%B0%D1%82%D0%B5%D0%B6%D0%B0): 
В блоке `receipt` устарел параметр **email**
> email
string, optional
Электронная почта пользователя для отправки чека.
Устарел — данные рекомендуется передавать в параметре **receipt.customer.email**

При внесении этих изменений:
```php
'receipt'=>[
   'customer'=>[
       'email'=>'email@email.com',
   ]
]
```
, вылетает  `YandexCheckout\Common\Exceptions\InvalidRequestException`
```php
Failed to build request "YandexCheckout\Request\Payments\CreatePaymentRequest": 
"Both email and phone values are empty in receipt"
```
Путь:  `lib/Common/AbstractPaymentRequest.php`
```php
        if ($this->_receipt !== null && $this->_receipt->notEmpty()) {
            $email = $this->_receipt->getEmail();
            $phone = $this->_receipt->getPhone();
            if (empty($email) && empty($phone)) {
                $this->setValidationError('Both email and phone values are empty in receipt');
                return false;
            }
        }
```

**Comment by ostulov** [comment]
Добрый день!

Благодарю за замечание! Мы в скором времени подготовим обновление SDK по новым требованиям.
При этом передача данных по-старому продолжает работать.

**Comment by ostulov** [comment]
Обновление доступно в релизе 1.2.5
