### ISSUE TITLE
Invalid payment data type "wechat"

### ISSUE THREAD

**Issue by SkyKaHub** [yandex-money/yandex-checkout-sdk-php#67]
Здравствуйте.

Invalid payment data type "wechat""
#0/home/c/cc89232/public_html/core/components/yandexkassaclient/Model/PaymentData/PaymentDataFactory.php(85): YandexCheckout\Model\PaymentData\PaymentDataFactory->factory('wechat') 
#1/home/c/cc89232/public_html/core/components/yandexkassaclient/Request/Payments/CreatePaymentRequestBuilder.php(202): YandexCheckout\Model\PaymentData\PaymentDataFactory->factoryFromArray(Array) 
#2/home/c/cc89232/public_html/core/components/yandexkassaclient/Common/AbstractRequestBuilder.php(112): YandexCheckout\Request\Payments\CreatePaymentRequestBuilder->setPaymentMethodData(Array)
#3/home/c/cc89232/public_html/core/components/yandexkassaclient/Request/Payments/CreatePaymentRequestBuilder.php(310): YandexCheckout\Common\AbstractRequestBuilder->setOptions(Array)

**Comment by ostulov** [comment]
Добрый день!

Способ оплаты WeChat в sdk еще не добавлен.
Рассмотрим возможность его внедрения.

**Comment by ostulov** [comment]
Добрый день!

Способ оплаты WeChat добавлен в сегодняшнем релизе 1.4.0.
