### ISSUE TITLE
Параметры receipt.email и receipt.phone устарели

### ISSUE THREAD

**Issue by merkuriy** [yandex-money/yandex-checkout-sdk-php#69]
SDK отстаёт от нововведений в API от [1 июля](https://kassa.yandex.ru/developers/changelog#1_июля).

Например, при создании платежа, SDK требует `receipt.email` или `receipt.phone` вместо `receipt.customer.email` или `receipt.customer.phone`.

**Comment by ostulov** [comment]
Добрый день!

Мы в скором времени подготовим обновление SDK по новым требованиям.
При этом передача данных по старому варианту продолжает работать.

**Comment by ostulov** [comment]
Обновление доступно в релизе 1.2.5
