### ISSUE TITLE
Проблема с длиной токена в YandexCheckout.js

### ISSUE THREAD

**Issue by ilyahoilik** [yandex-money/yandex-checkout-sdk-php#7]
Мне YandexCheckout.js возвращает токен длиной 424 символа, а так как [здесь](https://github.com/yandex-money/yandex-checkout-sdk-php/blob/21fbe4b02a76a83088a1d35c7b5981fd2fdcc6e2/lib/Request/Payments/CreatePaymentRequest.php#L240) выбрасывается исключение при длине более 200, то непонятно как нужно работать с этим функционалом.

Пример токена (тестовая карта 1111111111111026):

```
eyJlbmNyeXB0ZWQiOiI4MERDNjNZOFFwWHVnNUVHbTNZTnV6MUJrS1Rvc0VicUNhYUVPMFc5TmpYL04rZWp2U1ZzOHhsNkJCelJoRkRNWmFCSWVORHZsWXVEUUg2YzNvcXdiWU1rZXY1Q2dCdWVmNGxoY29XeUdLTVFiVEJ6TnRCYVlLTjRJdXJVS0g1MGYrTDlTYnRKRnh1RW9PRUQvaXpyZy96czJ5cTlpYkZ2L1orT05TTHJZTmw5ait0S0VsRXl5cm51L0xjTFozQUpSeTg9IiwiaW5pdFZlY3RvciI6Imx1Zk5TV0tibEhoV21lZ3pVaVo0YlE9PSIsImtleUlkIjoiT2pOQUJrL21Uam5kTGtWZlR1U1F0dz09IiwidHlwZSI6ImNoZWNrb3V0X2pzX2JhbmtfY2FyZCJ9
```

Подскажете что не так?

**Comment by actofgod** [comment]
не верно была написана спецификация, в ближайшем релизе поправим

**Comment by actofgod** [comment]
Баг исправлен в версии v1.0.3
