### ISSUE TITLE
B2b Налоговая ставка НДС

### ISSUE THREAD

**Issue by niceandriyanov** [yandex-money/yandex-checkout-sdk-php#76]
Здравствуйте. Добавьте пожалуйста 20% НДС в класс VatDataRate.
В доке яндекса сказано что поддерживается данный НДС: Налоговая ставка (в процентах). Возможные значения: 7, 10, 18 и 20.
Файл лежит: YandexCheckout\Model\PaymentData\B2b\Sberbank

**Comment by ostulov** [comment]
Благодарю за обращение, добавим.

**Comment by niceandriyanov** [comment]
А когда? Просто уже 12 дней прошло, на две строчки кода, очень много.

**Comment by ostulov** [comment]
Добрый день!

С нашей стороны процесс изменений может требовать больше времени.
Точный срок пока назвать не могу.

**Comment by ostulov** [comment]
Добрый день!

Мы выложили обновление 1.4.1, в нем доступна ставка 20% для Сбербанка Бизнес Онлайн.
