### ISSUE TITLE
Проблема с кастингом суммы платежа

### ISSUE THREAD

**Issue by AWSM3** [yandex-money/yandex-checkout-sdk-php#8]
**MonetaryAmount::setValue()** содержит следующий кастинг значения суммы:
`$castedValue = (int)round($value * 100.0);`
И по итогу объект имеет некорректную сумму платежа.
Вместо 10.00 рублей -- 1000. Это баг или так и должно быть?
Сделать пулл-реквест?

**Comment by actofgod** [comment]
Так и должно быть. Объекты класса MonetaryAmount хранят сумму платежа в копейках/центах.
