### ISSUE TITLE
Payment method is not available. Error code: invalid_request.

### ISSUE THREAD

**Issue by fidi87** [yandex-money/yandex-checkout-sdk-php#96]
В тестовом режиме работает, когда перевели на реальный режим, т.е. shopId и apiKey прописали ит реального магазина выскакивает ошибка "YandexCheckout\Common\Exceptions\BadApiRequestException
Payment method is not available. Error code: invalid_request."

**Comment by ostulov** [comment]
Добрый день!

Из возможных причин:
- действительно некорректный запрос
- передача способа оплаты, который не подключен магазину
- передача валюты, не подключенной магазину

Для определения точной причины нужны подробности. Пришлите на почту cms@yamoney.ru shopid, запрос или uuid-метку попытки.

**Comment by fidi87** [comment]
Видимо в яндексе что то отключили (или не включили). Написал тех поддержку. Они починили, проблема исчезла
